### ISSUE TITLE
Chinese encoding exception

### ISSUE THREAD

**Issue by j4587698** [Zeugma440/atldotnet#253]
## The problem

I have an MP3 file, which displays the title and artist correctly on Windows, but it shows up as garbled text in the library.

## Environment

* ATL version (or git revision) that exhibits the issue: Latest
* Last ATL version that did not exhibit the issue (if applicable):
* OS/version used to run ATL:Windows11

## Details

This screenshot is from viewing it on Windows, where 1 is the title, and 2 is the artist.
![image](https://github.com/Zeugma440/atldotnet/assets/24642446/bbf98660-76f9-41dd-bd1c-4876bd244948)

This screenshot is from the library.
![image](https://github.com/Zeugma440/atldotnet/assets/24642446/a5666b4b-c6bc-4ca8-9bd8-1a534496851a)
Wherein the artist has turned into garbled text.

My mp3 file is as follows.
[4249925507.zip](https://github.com/Zeugma440/atldotnet/files/14297601/4249925507.zip)

Could this be the same issue as #147 ?

**Comment by Zeugma440** [comment]
Hello there,

First of all, #147 is about a CUE file, not about an audio file. It's not the same issue.

The problem you have is as follows :
- Your file is tagged with ID3v1
- The ID3v1 specification does not set any encoding for strings. Most implementations use ANSI or Latin-1 (ISO-8859-1), but others simply use the device's default locale. That's probably what happened with your file which seems to have been tagged on a Chinese device
- The Windows explorer uses your default locale to decode ID3v1 strings, that's why it is able to read it properly
- ATL uses hardcoded Latin-1 to decode and encode ID3v1 strings
 
One possible solution would be to make ATL decode and encode ID3v1 strings with `Settings.DefaultTextEncoding`, which you could set to `Encoding.Default` to be able to handle Chinese strings... But then you'd have issue handling _western_ ID3v1 tags which are _actually_ using Latin-1 encoding 😅 

Is that worth trying?

**Comment by j4587698** [comment]
![image](https://github.com/Zeugma440/atldotnet/assets/24642446/76097c54-b2cb-42f1-a253-1704a3f6e039)

I tried using Default and GB2312, but the content is still garbled

**Comment by j4587698** [comment]
Could we try to perform encoding detection on id3v1? I remember that encoding detection can distinguish between ANSI and Latin-1, and since id3v1 is not large, only 128 bytes, the detection speed should be acceptable.

**Comment by Zeugma440** [comment]
> Could we try to perform encoding detection on id3v1? I remember that encoding detection can distinguish between ANSI and Latin-1, and since id3v1 is not large, only 128 bytes, the detection speed should be acceptable.

I actually tried that yesterday, trying both [UDE](https://github.com/errepi/ude) and [UTF-Unknown](https://github.com/CharsetDetector/UTF-unknown). Unfortunately, there's not enough data for the encoding detection to succeed, especially on the file you submitted where there are 10 valid bytes to play with.

> I tried using Default and GB2312, but the content is still garbled

What I wrote was a suggestion to see if you'd agree. Latest version of ATL doesn't use `Settings.DefaultTextEncoding` to decode ID3v1. Does that mean I can go that way?

**Comment by j4587698** [comment]
Yes, you are right. However, since Latin-1 is a lossless mapping, I might be able to handle this issue on my own. I can re-parse the string into bytes, and then proceed with the Chinese character determination. Simply determining Chinese characters is straightforward, as GB2312 has certain regularities, as do BIG5, Shift-JIS, EUC-KR, and others. However, this kind of regularity might lead to some errors in the determination of certain Western characters. But under circumstances with a certain bias, it should be acceptable.

**Comment by Zeugma440** [comment]
Sounds feasible too. Let me know if you need anything 👍 

I'll close the issue in 30 days if nothing happened.
