### ISSUE TITLE
M4a files will add lower and uppercase additional fields

### ISSUE THREAD

**Issue by sandreas** [Zeugma440/atldotnet#289]
Using this code:

```c#
var dst = "sample.m4a";

var track = new Track(dst);
track.AdditionalFields["©nrt"] = "Narrator Name";
await track.SaveAsync();
```

Will add `©nrt` and `©NRT` to the tags... is that expected behaviour?

```bash
>  tone dump sample.m4a --format=json --query='$.meta'
{
  "title": "testing",
  "additionalFields": {
    "©NRT": "Narrator Name",
    "©nrt": "Narrator Name"
  }
}

```

**Comment by Zeugma440** [comment]
Hi there,

I've been very busy with another project lately. I'll take care of that issue when things have calmed down.

Thanks for your understanding~

**Comment by sandreas** [comment]
> Thanks for your understanding~

I probably understand better than you think :-) Thanks for the feedback.

**Comment by Zeugma440** [comment]
That's because with the default settings (`Settings.DefaultTagsWhenNoMetadata = { MetaDataIOFactory.TagType.RECOMMENDED }`), your instructions actually create :
- One `©nrt` field inside the M4A native metadata structure (`udta.meta.ilst`)
- One `@nrt` field inside a brand new APEtag structure added to the file

That's kinda dumb as the MP4 native tagging system is rich enough not to need an APEtag clutch.

=> I've changed the default behaviour so that MP4, FLAC, OGG, MKA and WMA write into their native tagging system alone in that case.

**Comment by Zeugma440** [comment]
Fix has been delivered in today's v6.09.

Please close the issue if it works on your side.

**Comment by sandreas** [comment]
Thanks, I'll report back as soon as I tested.

**Comment by sandreas** [comment]
Works like a charm. Thank you very much...
