### ISSUE TITLE
Question about a picture of a Track.

### ISSUE THREAD

**Issue by Smiuv** [Zeugma440/atldotnet#298]
Hello,
Some users message me and complain about the images they put for a song and that they are not displayed in their music player.
I tried it myself, they are not displayed in *Android music players*. But they are displayed in a player like *MX Player*.

I also tried it on Windows, some of them are only displayed in video players like *VLC* and *KMPlayer* and they are not displayed in Windows' own music player.

Thank you.

**Comment by Smiuv** [comment]
I noticed something but I'm not sure how accurate it is.

A music file with an image is **796** KB and when I remove the image and then add the image back to it (the same image) the file size is reduced to **795 KB**.

**Comment by Zeugma440** [comment]
Hi there,

Could you be more precise about the files formats we're talking about (e.g. MP3,FLAC,OGG,M4A)?

If you're using ID3v2 to tag, maximum compatibility is ensured by tagging with  ID3v2.3 instead of default ID3v2.4.

You can do that by calling `ATL.Settings.ID3v2_tagSubVersion = 3` during the init phase of your app.

Last but not least, "Android music players" is not precise enough for me to reproduce that issue. Android itself comes in many versions, devices come with bundled manufacturer apps, plus users can install 3rd party apps through the store. 
=> If Android devices are an issue indeed, I'd need the name of the specific player app name to be able to reproduce that one.

Please keep me informed.

**Comment by Smiuv** [comment]
I changed these setting and it worked, thank you.
