### ISSUE TITLE
Can't set the WOAR value correctly.

### ISSUE THREAD

**Issue by inetmarketeers** [Zeugma440/atldotnet#85]
## The problem

So I have tried to set this value as an addition field

            theTrack.AdditionalFields["WOAR"] = textEdit3.Text;

## Environment

Visual Studio 19
using ATL 3.16

## Details
The value does not get saved at least when I open the file again the WOAR value is null. 
I

**Comment by Zeugma440** [comment]
Hey there !

I've tested it myself and it seems to work fine on my end.

The issue you have might be caused by :
- Incorrect writing code (you just sent one single line here)
- Incorrect reading code
- Using WOAR with ID3v2.3 (shouldn't happen if you're using ATL default settings)
- Trying to write to a file format that doesn't support additional fields (e.g. S3M or MIDI)

Could you give a little more details so that I can help you find the issue ?  I advise you to start opening your audio file with an editor and check if the field has actually been written.

**Comment by inetmarketeers** [comment]
Sure, here is my code

            Settings.ID3v2_tagSubVersion = 3;
            Track theTrack = new Track(filename);
            theTrack.AlbumArtist = textEdit2.Text;
            theTrack.AdditionalFields["WOAR"] = textEdit3.Text;
            theTrack.Popularity = 255;
            theTrack.Save();

Popularity is saved correctly. the textEdit3.Text will have for example https://therankingstore.com 

However when I read the same file with the component the key value is like this:

"ÿþh\0t\0t\0p\0s\0:\0/\0/\0w\0w\0w\0.\0t\0h\0e\0r\0a\0n\0k\0i\0n\0g\0s\0t\0o\0r\0e\0.\0c\0o\0m\0/"

**Comment by Zeugma440** [comment]
Thanks for the details. 

I'll try with that and let you know tomorrow.

**Comment by Zeugma440** [comment]
There was indeed an issue when writing URL link frames with the ID3v2.3 format.

The fix will be available in the next release.

**Comment by inetmarketeers** [comment]
Do you have any timeframe for that release?

**Comment by inetmarketeers** [comment]
Or is there a workaround?

**Comment by Zeugma440** [comment]
Timeframe : Today or tomorrow
Workaround : Use ID3v2.4 😁 😁

**Comment by inetmarketeers** [comment]
Fantastic

**Comment by Zeugma440** [comment]
That's done !  Fix is available on today's v3.17.

Enjoy~
